import { useState } from 'react'
import { Check, Pencil, Plus, Trash2, X } from 'lucide-react'
import type { KeepsyCollection } from '../types'
import { Button } from './ui/Button'
import { EmptyState } from './EmptyState'
import { labelColor } from '../lib/colorLabels'

export function CollectionManager({ collections, counts, onCreate, onRename, onDelete }: { collections: KeepsyCollection[]; counts: Record<string, number>; onCreate: (name: string) => Promise<KeepsyCollection>; onRename: (id: string, name: string) => Promise<void>; onDelete: (id: string) => Promise<void> }) {
  const [newName, setNewName] = useState('')
  const [editing, setEditing] = useState<string | null>(null)
  const [editName, setEditName] = useState('')
  const [confirmDelete, setConfirmDelete] = useState<string | null>(null)
  const [error, setError] = useState('')
  const create = async () => { try { await onCreate(newName); setNewName(''); setError('') } catch (reason) { setError((reason as Error).message) } }
  const rename = async () => { if (!editing) return; try { await onRename(editing, editName); setEditing(null); setError('') } catch (reason) { setError((reason as Error).message) } }

  return <div className="space-y-4">
    <div className="flex gap-2"><input value={newName} onChange={event => setNewName(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); void create() } }} placeholder="New collection name" className="min-w-0 flex-1 rounded-xl border border-line bg-card px-3 py-2.5 text-xs outline-none transition focus:border-primary/70 focus:ring-4 focus:ring-primary/10" /><Button type="button" disabled={!newName.trim()} onClick={() => { void create() }} className="px-3"><Plus size={14} />Add</Button></div>
    {error && <p role="alert" className="text-xs text-[#ff9fb5]">{error}</p>}
    {collections.length === 0 ? <EmptyState title="No collections yet" detail="Create your first collection to start organizing saved items." /> : <div className="max-h-[350px] space-y-1.5 overflow-y-auto">{collections.map(collection => <div key={collection.id} className="flex items-center gap-2 rounded-xl border border-line bg-card p-2.5">{editing === collection.id ? <><input autoFocus value={editName} onChange={event => setEditName(event.target.value)} onKeyDown={event => { if (event.key === 'Enter') { event.preventDefault(); void rename() } }} className="min-w-0 flex-1 rounded-lg border border-line bg-surface px-2 py-1.5 text-xs outline-none focus:border-primary/70" /><button onClick={() => { void rename() }} aria-label={`Save ${collection.name}`} className="grid size-7 place-items-center rounded-lg text-[#81b0ff] transition hover:bg-primary/10 focus:outline-none focus:ring-2 focus:ring-primary"><Check size={14} /></button><button onClick={() => setEditing(null)} aria-label="Cancel rename" className="grid size-7 place-items-center rounded-lg text-muted transition hover:bg-white/[.05] focus:outline-none focus:ring-2 focus:ring-primary"><X size={14} /></button></> : <><span className="size-2 shrink-0 rounded-full" style={{ backgroundColor: labelColor(collection.name).text }} /><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-[#E6E8F0]">{collection.name}</p><p className="mt-0.5 text-[10px] text-muted">{counts[collection.id] || 0} item{counts[collection.id] === 1 ? '' : 's'}</p></div><button onClick={() => { setEditing(collection.id); setEditName(collection.name); setConfirmDelete(null) }} aria-label={`Rename ${collection.name}`} className="grid size-7 place-items-center rounded-lg text-muted transition hover:bg-white/[.05] hover:text-white focus:outline-none focus:ring-2 focus:ring-primary"><Pencil size={13} /></button>{confirmDelete === collection.id ? <><button onClick={() => { void onDelete(collection.id); setConfirmDelete(null) }} className="rounded-lg bg-[#c94166]/15 px-2 py-1.5 text-[10px] font-medium text-[#ff9fb5] transition hover:bg-[#c94166]/25 focus:outline-none focus:ring-2 focus:ring-primary">Delete</button><button onClick={() => setConfirmDelete(null)} aria-label="Cancel delete" className="grid size-7 place-items-center rounded-lg text-muted transition hover:bg-white/[.05] focus:outline-none focus:ring-2 focus:ring-primary"><X size={13} /></button></> : <button onClick={() => setConfirmDelete(collection.id)} aria-label={`Delete ${collection.name}`} className="grid size-7 place-items-center rounded-lg text-muted transition hover:bg-[#ff5577]/10 hover:text-[#ff8ca7] focus:outline-none focus:ring-2 focus:ring-primary"><Trash2 size={13} /></button>}</>}</div>)}</div>}
  </div>
}
