import { useState } from 'react'
import { LoaderCircle, Plus } from 'lucide-react'
import { walletNetworks, type ItemDraft, type ItemType, type KeepsyCollection, type KeepsyItem, type WalletNetwork } from '../types'
import { Button } from './ui/Button'
import { IconPicker } from './IconPicker'
import { TypeSelect } from './TypeSelect'
import { SearchableSelect } from './ui/SearchableSelect'
import { getYouTubeMetadata, validHttpUrl, validWallet } from '../lib/specialized'
import { loadTypePreference, saveTypePreference } from '../lib/preferences'
import { useTags } from '../lib/taxonomy'
import { CollectionSelect } from './CollectionSelect'
import { suggestedCollectionNames } from '../lib/collectionSuggestions'

const input = 'mt-1 w-full rounded-xl border border-line bg-card px-3 py-2.5 text-[13px] text-[#E6E8F0] outline-none focus:border-primary/70 focus:ring-4 focus:ring-primary/10'
const smart = (type: ItemType): [string, string[]] => type === 'Crypto Wallet' ? ['Crypto', ['Wallet']] : type === 'YouTube' ? ['Learning', ['YouTube', 'Tutorial']] : type === 'API Key' ? ['Development', ['API']] : type === 'Code' ? ['Development', ['React']] : ['Personal', ['Personal']]
export function ItemForm({ item, collections, onCreateCollection, onSave, onCancel }: { item?: KeepsyItem; collections: KeepsyCollection[]; onCreateCollection: (name: string) => Promise<KeepsyCollection>; onSave: (draft: ItemDraft) => Promise<void>; onCancel: () => void }) {
  const [draft, setDraft] = useState<ItemDraft>(() => item ? { ...item, collectionIds: item.collectionIds || [] } : { type: 'Note', title: '', content: '', category: 'Personal', tags: ['Personal'], collectionIds: [] }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [fetchingYoutube, setFetchingYoutube] = useState(false)
  const set = <K extends keyof ItemDraft>(key: K, value: ItemDraft[K]) => setDraft(current => ({ ...current, [key]: value }))
  const field = (label: string, key: keyof ItemDraft, placeholder: string, type = 'text') => <label className="block text-[11px] font-medium text-muted">{label}<input type={type} value={(draft[key] as string) || ''} onChange={e => set(key, e.target.value)} placeholder={placeholder} className={input} /></label>
  const fetchYoutube = async () => { if (!draft.url) return; setFetchingYoutube(true); try { const metadata = await getYouTubeMetadata(draft.url); if (metadata) setDraft(current => ({ ...current, title: current.title || metadata.title, youtubeThumbnail: metadata.thumbnail, youtubeChannel: metadata.channel, type: 'YouTube', category: 'Learning', tags: Array.from(new Set([...current.tags, 'YouTube', 'Tutorial'])) })) } finally { setFetchingYoutube(false) } }
  const extra = draft.type === 'Code' ? <><label className="block text-[11px] font-medium text-muted">Language<select value={draft.language || 'TypeScript'} onChange={e => set('language', e.target.value)} className={input}>{['TypeScript','JavaScript','Python','JSON','HTML','CSS','SQL','Bash'].map(x => <option key={x}>{x}</option>)}</select></label><label className="block text-[11px] font-medium text-muted">Snippet<textarea value={draft.code || ''} onChange={e => set('code', e.target.value)} className={`${input} min-h-28 font-mono text-xs`} /></label></> : draft.type === 'Crypto Wallet' ? <>{field('Wallet name','walletName','Main wallet')}<label className="block text-[11px] font-medium text-muted">Network<select value={draft.walletNetwork || 'ETH'} onChange={e => set('walletNetwork', e.target.value as WalletNetwork)} className={input}>{walletNetworks.map(network => <option key={network}>{network}</option>)}</select></label><label className="block text-[11px] font-medium text-muted">Address<input value={draft.walletAddress || ''} onChange={e => set('walletAddress', e.target.value)} className={input} /></label></> : draft.type === 'API Key' ? field('API key','apiKey','Paste API key','password') : draft.type === 'Email' ? field('Email','email','name@example.com','email') : draft.type === 'Phone' ? field('Phone','phone','+1 555...','tel') : draft.type === 'Website' || draft.type === 'YouTube' ? <label className="block text-[11px] font-medium text-muted">URL<span className="relative mt-1 block"><input value={draft.url || ''} onChange={e => set('url', e.target.value)} onBlur={() => { void fetchYoutube() }} placeholder="https://" type="url" className={`${input} mt-0 ${fetchingYoutube ? 'pr-9' : ''}`} />{fetchingYoutube && <LoaderCircle size={15} className="absolute right-3 top-1/2 -translate-y-1/2 animate-spin text-[#81b0ff]" />}</span></label> : <label className="block text-[11px] font-medium text-muted">Details<textarea value={draft.content || ''} onChange={e => set('content', e.target.value)} className={`${input} min-h-20`} /></label>
  const [category, tags] = smart(draft.type)
  const suggestedCollectionIds = collections.filter(collection => suggestedCollectionNames(draft.type).some(name => name.toLocaleLowerCase() === collection.name.toLocaleLowerCase())).map(collection => collection.id)
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!draft.title.trim()) return setError('Add a title before saving.'); if ((draft.type === 'Website' || draft.type === 'YouTube') && draft.url && !validHttpUrl(draft.url)) return setError('Use a valid http or https link.'); if (draft.type === 'Crypto Wallet' && draft.walletAddress && !validWallet(draft.walletAddress, draft.walletNetwork || 'ETH')) return setError(`Enter a valid ${draft.walletNetwork || 'ETH'} wallet address.`); setSaving(true); try { await saveTypePreference(draft.type, { category: draft.category, tags: draft.tags }); await useTags(draft.tags); await onSave({ ...draft, title: draft.title.trim() }) } catch { setError('Could not save this item.') } finally { setSaving(false) } }
  const selectType = async (type: ItemType) => { const [nextCategory, nextTags] = smart(type); const preference = item ? null : await loadTypePreference(type); setDraft(current => ({ ...current, type, category: item ? current.category : preference?.category || nextCategory, tags: item ? current.tags : preference?.tags || nextTags })) }
  return <form onSubmit={submit} className="space-y-3.5"><TypeSelect value={draft.type} onChange={type => { void selectType(type) }} /><label className="block text-[11px] font-medium text-muted">Title<input value={draft.title} onChange={e => set('title',e.target.value)} placeholder="Give it a clear name" className={input} /></label><div className="space-y-3">{extra}</div><IconPicker type={draft.type} icon={draft.customIcon} onChange={value => setDraft(current => ({ ...current, ...value }))} /><div className="grid grid-cols-2 gap-3"><SearchableSelect kind="categories" label="Category" value={draft.category} onChange={value => set('category',value as string)} placeholder="Choose category" suggested={[category]} /><SearchableSelect kind="tags" label="Tags" multiple value={draft.tags} onChange={value => set('tags',value as string[])} placeholder="Choose tags" suggested={tags} /></div><CollectionSelect collections={collections} value={draft.collectionIds || []} onChange={value => set('collectionIds', value)} onCreate={onCreateCollection} suggestedIds={suggestedCollectionIds} />{error && <p role="alert" className="text-xs text-[#ff9fb5]">{error}</p>}<div className="flex justify-end gap-2 border-t border-line pt-4"><Button type="button" variant="ghost" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={saving || fetchingYoutube}><Plus size={15} />{saving ? 'Saving...' : fetchingYoutube ? 'Fetching...' : item ? 'Save changes' : 'Save item'}</Button></div></form>
}
