import { useState } from 'react'
import { AlertTriangle, Link2, Plus, Sparkles } from 'lucide-react'
import type { CapturePayload, ItemDraft, KeepsyCollection } from '../types'
import { Button } from './ui/Button'
import { SearchableSelect } from './ui/SearchableSelect'
import { TypeSelect } from './TypeSelect'
import { useTags } from '../lib/taxonomy'
import { CollectionSelect } from './CollectionSelect'
import { suggestedCollectionNames } from '../lib/collectionSuggestions'

const fieldStyle = 'mt-1 w-full rounded-xl border border-line bg-card px-3 py-2.5 text-[13px] text-[#E6E8F0] outline-none transition-all duration-200 placeholder:text-muted/65 focus:border-primary/70 focus:ring-4 focus:ring-primary/10'

function toDraft(capture: CapturePayload): ItemDraft { return { type: capture.type, title: capture.title, category: capture.category, tags: capture.tags, collectionIds: [], content: capture.content, url: capture.url, faviconUrl: capture.faviconUrl, email: capture.email, phone: capture.phone, walletAddress: capture.walletAddress } }

export function QuickSaveForm({ capture, duplicate, collections, onCreateCollection, onSave, onCancel }: { capture: CapturePayload; duplicate: boolean; collections: KeepsyCollection[]; onCreateCollection: (name: string) => Promise<KeepsyCollection>; onSave: (draft: ItemDraft) => Promise<void>; onCancel: () => void }) {
  const [draft, setDraft] = useState<ItemDraft>(() => toDraft(capture)); const [saving, setSaving] = useState(false); const [error, setError] = useState('')
  const set = <K extends keyof ItemDraft>(key: K, value: ItemDraft[K]) => setDraft(current => ({ ...current, [key]: value }))
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!draft.title.trim()) return setError('Add a title to save this capture.'); setSaving(true); try { await useTags(draft.tags); await onSave({ ...draft, title: draft.title.trim(), category: draft.category || 'Personal' }) } catch { setError('Keepsy could not save this capture. Please try again.') } finally { setSaving(false) } }
  const sourceLabel = capture.source === 'page' ? 'Current page' : capture.source === 'link' ? 'Link' : 'Selected text'
  const suggestedCollectionIds = collections.filter(collection => suggestedCollectionNames(draft.type).some(name => name.toLocaleLowerCase() === collection.name.toLocaleLowerCase())).map(collection => collection.id)
  return <form onSubmit={submit} className="space-y-4"><div className="flex items-center gap-3 rounded-xl border border-primary/20 bg-primary/[.07] p-3"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-primary/15 text-[#81b0ff]"><Sparkles size={16} strokeWidth={1.8} /></div><div className="min-w-0"><p className="text-[11px] font-medium text-[#81b0ff]">Ready to save</p><p className="mt-0.5 truncate text-xs text-muted">Captured from {sourceLabel.toLowerCase()}</p></div></div>{duplicate && <div role="alert" className="flex gap-2 rounded-xl border border-[#694a22] bg-[#241b10] p-3 text-[11px] leading-4 text-[#f5c878]"><AlertTriangle size={15} className="shrink-0" />A similar item is already saved. You can still save another copy.</div>}<label className="block text-[11px] font-medium text-muted">Title<input value={draft.title} onChange={e => set('title', e.target.value)} className={fieldStyle} autoFocus /></label><div className="grid grid-cols-2 gap-3"><TypeSelect value={draft.type} onChange={type => set('type', type)} /><SearchableSelect kind="categories" label="Category" value={draft.category} onChange={value => set('category', value as string)} placeholder="Choose category" suggested={[capture.category]} /></div>{(draft.url || draft.email || draft.phone || draft.walletAddress || draft.content) && <div className="flex items-start gap-2 rounded-xl border border-line bg-card px-3 py-2.5 text-[11px] text-muted"><Link2 size={14} className="mt-0.5 shrink-0 text-[#81b0ff]" /><span className="line-clamp-2 break-all">{draft.url || draft.email || draft.phone || draft.walletAddress || draft.content}</span></div>}<SearchableSelect kind="tags" label="Tags" multiple value={draft.tags} onChange={value => set('tags', value as string[])} placeholder="Choose tags" suggested={capture.tags} /><CollectionSelect collections={collections} value={draft.collectionIds || []} onChange={value => set('collectionIds', value)} onCreate={onCreateCollection} suggestedIds={suggestedCollectionIds} />{error && <p role="alert" className="text-xs text-[#ff9fb5]">{error}</p>}<div className="flex justify-end gap-2 border-t border-line pt-4"><Button type="button" variant="ghost" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={saving}><Plus size={15} />{saving ? 'Saving...' : duplicate ? 'Save anyway' : 'Save capture'}</Button></div></form>
}
