import { lazy, Suspense, useEffect, useMemo, useRef, useState } from 'react'
import { CheckCircle2, ChevronLeft, ChevronRight, Eye, EyeOff, FolderInput, Gamepad2, Layers3, ListChecks, LoaderCircle, Plus, QrCode, Search, Settings2, SlidersHorizontal, Tag, Trash2, TriangleAlert, X } from 'lucide-react'
import { AnimatePresence, motion, MotionConfig } from 'framer-motion'
import { Brand } from './components/Brand'
import { EmptyState } from './components/EmptyState'
import { ItemForm } from './components/ItemForm'
import { ItemIcon } from './components/ItemIcon'
import { QuickSaveForm } from './components/QuickSaveForm'
import { SaveItemCard } from './components/SaveItemCard'
import { Button } from './components/ui/Button'
import { Modal } from './components/ui/Modal'
import { WalletQr } from './components/WalletQr'
import { ProductivityPanel } from './components/ProductivityPanel'
import { SearchableSelect } from './components/ui/SearchableSelect'
import { CollectionSelect } from './components/CollectionSelect'
import { CollectionManager } from './components/CollectionManager'
import { TaxonomyManager } from './components/TaxonomyManager'
import { CustomIconsGallery } from './components/CustomIconsGallery'
import { Settings } from './components/Settings'
import { Onboarding } from './components/Onboarding'
import { useItems } from './hooks/useItems'
import { useCollections } from './hooks/useCollections'
import { clearPendingCapture, loadPendingCapture, storageKeys } from './lib/storage'
import { addTaxonomy, loadTaxonomy, removeTaxonomy, resetTaxonomy, saveTaxonomy, taxonomyStorageKey } from './lib/taxonomy'
import { defaultSettings, loadSettings, saveSettings, settingsStorageKey, type Settings as SettingsData } from './lib/settings'
import { loadOnboardingCompleted, setOnboardingCompleted } from './lib/onboarding'
import { labelColor } from './lib/colorLabels'
import { Badge } from './components/ui/Badge'
import { itemTypes, type CapturePayload, type Filter, type ItemDraft, type KeepsyCollection, type KeepsyItem, type SortMode } from './types'
import { domainFromUrl, highlightCode, walletExplorer } from './lib/specialized'

const TapTheDot = lazy(() => import('./games/tap-the-dot/TapTheDot'))
const GamesHub = lazy(() => import('./games/GamesHub'))
const filters: Filter[] = ['All', 'Recent', 'Favorites', 'Pinned']
const valueForCopy = (item: KeepsyItem) => item.url || item.email || item.phone || item.walletAddress || item.apiKey || item.code || item.content || item.title

export function App() {
  const store = useItems(); const collectionStore = useCollections(); const [filter, setFilter] = useState<Filter>('All'); const [collectionFilter, setCollectionFilter] = useState<string | null>(null); const [query, setQuery] = useState(''); const [editor, setEditor] = useState<KeepsyItem | 'new' | null>(null); const [detail, setDetail] = useState<KeepsyItem | null>(null); const [confirm, setConfirm] = useState<{ item: KeepsyItem; permanent: boolean } | null>(null); const [notice, setNotice] = useState<string | null>(null); const [quickCapture, setQuickCapture] = useState<CapturePayload | null>(null); const [showSecret, setShowSecret] = useState(false); const [qrItem, setQrItem] = useState<KeepsyItem | null>(null); const [panel, setPanel] = useState(false); const [manageCollections, setManageCollections] = useState(false); const [quickCollectionItem, setQuickCollectionItem] = useState<KeepsyItem | null>(null); const [quickCollectionIds, setQuickCollectionIds] = useState<string[]>([]); const [bulkMode, setBulkMode] = useState(false); const [selected, setSelected] = useState<Set<string>>(new Set()); const [bulkEditor, setBulkEditor] = useState<'category' | 'tags' | 'collections' | null>(null); const [bulkCategory, setBulkCategory] = useState(''); const [bulkTags, setBulkTags] = useState<string[]>([]); const [bulkCollections, setBulkCollections] = useState<string[]>([]); const [tagOperation, setTagOperation] = useState<'add' | 'remove'>('add'); const [collectionOperation, setCollectionOperation] = useState<'add' | 'remove'>('add'); const [bulkDelete, setBulkDelete] = useState(false); const [undoItems, setUndoItems] = useState<KeepsyItem[] | null>(null); const [advanced, setAdvanced] = useState({ type: '', category: '', tag: '', favorite: false, pinned: false, sort: 'newest' as SortMode })
  const [taxonomy, setTaxonomy] = useState<{ categories: string[]; tags: string[] }>({ categories: [], tags: [] })
  const [settings, setSettings] = useState<SettingsData>(defaultSettings)
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [manageCategories, setManageCategories] = useState(false)
  const [manageTags, setManageTags] = useState(false)
  const [customIconsOpen, setCustomIconsOpen] = useState(false)
  const [storageBytes, setStorageBytes] = useState<number | null>(null)
  const [onboardingOpen, setOnboardingOpen] = useState(false)
  const [tapTheDotOpen, setTapTheDotOpen] = useState(false)
  const [gamesHubOpen, setGamesHubOpen] = useState(false)
  const collectionsScrollRef = useRef<HTMLDivElement>(null); const [canScrollLeft, setCanScrollLeft] = useState(false); const [canScrollRight, setCanScrollRight] = useState(false)
  const updateCollectionsScroll = () => { const el = collectionsScrollRef.current; if (!el) return; setCanScrollLeft(el.scrollLeft > 4); setCanScrollRight(el.scrollLeft + el.clientWidth < el.scrollWidth - 4) }
  const scrollCollections = (direction: number) => collectionsScrollRef.current?.scrollBy({ left: direction * 168, behavior: 'smooth' })
  const pillRefs = useRef<Map<string, HTMLButtonElement>>(new Map())
  useEffect(() => { updateCollectionsScroll() }, [collectionStore.collections, filter])
  useEffect(() => { pillRefs.current.get(collectionFilter ?? 'all')?.scrollIntoView({ behavior: 'smooth', inline: 'nearest', block: 'nearest' }) }, [collectionFilter])
  const active = store.items.filter(item => !item.deletedAt); const trashed = store.items.filter(item => item.deletedAt)
  const collectionCounts = useMemo(() => Object.fromEntries(collectionStore.collections.map(collection => [collection.id, active.filter(item => (item.collectionIds || []).includes(collection.id)).length])), [collectionStore.collections, active])
  const shown = useMemo(() => { const source = filter === 'Trash' ? trashed : active; let result = source.filter(item => { const collectionNames = (item.collectionIds || []).map(id => collectionStore.collections.find(collection => collection.id === id)?.name || '').join(' '); return `${item.title} ${item.category} ${item.tags.join(' ')} ${collectionNames} ${valueForCopy(item)}`.toLowerCase().includes(query.toLowerCase()) }); if (collectionFilter && filter !== 'Trash') result = result.filter(item => (item.collectionIds || []).includes(collectionFilter)); if (filter === 'Favorites' || advanced.favorite) result = result.filter(i => i.favorite); if (filter === 'Pinned' || advanced.pinned) result = result.filter(i => i.pinned); if (advanced.type) result = result.filter(i => i.type === advanced.type); if (advanced.category) result = result.filter(i => i.category === advanced.category); if (advanced.tag) result = result.filter(i => i.tags.includes(advanced.tag)); const sorted = [...result]; sorted.sort((a,b) => advanced.sort === 'oldest' ? a.createdAt.localeCompare(b.createdAt) : advanced.sort === 'updated' ? b.updatedAt.localeCompare(a.updatedAt) : advanced.sort === 'az' ? a.title.localeCompare(b.title) : b.createdAt.localeCompare(a.createdAt)); return sorted }, [active, trashed, filter, collectionFilter, collectionStore.collections, query, advanced])
  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 2400) }
  const selectedIds = Array.from(selected)
  const toggleSelected = (id: string) => setSelected(current => { const next = new Set(current); next.has(id) ? next.delete(id) : next.add(id); return next })
  const deleteToTrash = async (ids: string[]) => { const deleted = store.items.filter(item => ids.includes(item.id) && !item.deletedAt); if (!deleted.length) return; await store.bulk(ids, { trash: true }); setSelected(new Set()); setUndoItems(deleted); setNotice(`${deleted.length} item${deleted.length === 1 ? '' : 's'} moved to Trash.`); window.setTimeout(() => setNotice(null), 6000); window.setTimeout(() => setUndoItems(current => current === deleted ? null : current), 6000) }
  const undoDelete = async () => { if (!undoItems) return; await Promise.all(undoItems.map(item => store.restore(item.id))); setUndoItems(null); flash('Deletion undone.') }
  const applyBulk = async () => { if (!selectedIds.length) return; if (bulkEditor === 'category' && bulkCategory) { await store.bulk(selectedIds, { category: bulkCategory }); flash(`Moved ${selectedIds.length} items to ${bulkCategory}.`) } if (bulkEditor === 'tags' && bulkTags.length) { await store.bulk(selectedIds, tagOperation === 'add' ? { addTags: bulkTags } : { removeTags: bulkTags }); flash(`Tags ${tagOperation === 'add' ? 'added to' : 'removed from'} ${selectedIds.length} items.`) } if (bulkEditor === 'collections' && bulkCollections.length) { await store.bulk(selectedIds, collectionOperation === 'add' ? { addCollections: bulkCollections } : { removeCollections: bulkCollections }); if (collectionOperation === 'add') await collectionStore.touch(bulkCollections); flash(`Collections ${collectionOperation === 'add' ? 'added to' : 'removed from'} ${selectedIds.length} items.`) } setBulkEditor(null); setBulkTags([]); setBulkCollections([]) }
  useEffect(() => { setSelected(current => { const nextIds = Array.from(current).filter(id => store.items.some(item => item.id === id && !item.deletedAt)); if (nextIds.length === current.size) return current; return new Set(nextIds) }) }, [store.items])
  useEffect(() => { loadPendingCapture().then(setQuickCapture).catch(() => undefined); if (typeof chrome === 'undefined' || !chrome.storage?.onChanged) return; const listener = (changes: { [key: string]: chrome.storage.StorageChange }, area: string) => { if (area === 'local' && changes[storageKeys.pendingCapture]?.newValue) setQuickCapture(changes[storageKeys.pendingCapture].newValue as CapturePayload) }; chrome.storage.onChanged.addListener(listener); return () => chrome.storage.onChanged.removeListener(listener) }, [])
  useEffect(() => { loadTaxonomy().then(setTaxonomy).catch(() => undefined); if (typeof chrome === 'undefined' || !chrome.storage?.onChanged) return; const listener = (changes: { [key: string]: chrome.storage.StorageChange }, area: string) => { if (area === 'local' && changes[taxonomyStorageKey]) void loadTaxonomy().then(setTaxonomy) }; chrome.storage.onChanged.addListener(listener); return () => chrome.storage.onChanged.removeListener(listener) }, [])
  useEffect(() => { loadSettings().then(loaded => { setSettings(loaded); setFilter(loaded.defaultHomeView); setAdvanced(current => ({ ...current, sort: loaded.defaultSort })) }).catch(() => undefined); if (typeof chrome === 'undefined' || !chrome.storage?.onChanged) return; const listener = (changes: { [key: string]: chrome.storage.StorageChange }, area: string) => { if (area === 'local' && changes[settingsStorageKey]) void loadSettings().then(setSettings) }; chrome.storage.onChanged.addListener(listener); return () => chrome.storage.onChanged.removeListener(listener) }, [])
  useEffect(() => { if (store.loading || settings.autoEmptyTrash === 'never') return; const cutoffMs = Date.now() - Number(settings.autoEmptyTrash) * 24 * 60 * 60 * 1000; const stale = store.items.filter(item => item.deletedAt && new Date(item.deletedAt).getTime() < cutoffMs); if (stale.length) void store.replace(store.items.filter(item => !stale.includes(item))) }, [store.loading, store.items, settings.autoEmptyTrash])
  useEffect(() => { if (!settingsOpen) return; if (typeof chrome !== 'undefined' && chrome.storage?.local?.getBytesInUse) { chrome.storage.local.getBytesInUse(null, bytes => setStorageBytes(bytes)) } else { setStorageBytes(new Blob([JSON.stringify(store.items), JSON.stringify(collectionStore.collections), JSON.stringify(taxonomy), JSON.stringify(settings)]).size) } }, [settingsOpen, store.items, collectionStore.collections, taxonomy, settings])
  useEffect(() => { loadOnboardingCompleted().then(completed => { if (!completed) setOnboardingOpen(true) }).catch(() => undefined) }, [])
  const finishOnboarding = () => { setOnboardingOpen(false); void setOnboardingCompleted(true) }
  useEffect(() => { const keys = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); document.querySelector<HTMLInputElement>('[aria-label="Search saved items"]')?.focus() } if (event.key === '/' && document.activeElement?.tagName !== 'INPUT') { event.preventDefault(); document.querySelector<HTMLInputElement>('[aria-label="Search saved items"]')?.focus() } if (event.key === 'Escape') { setEditor(null); setDetail(null); setPanel(false) } }; window.addEventListener('keydown', keys); return () => window.removeEventListener('keydown', keys) }, [])
  const exportBackup = () => { const backup = { version: 1, items: store.items, collections: collectionStore.collections, taxonomy, settings }; const blob = new Blob([JSON.stringify(backup, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'keepsy-backup.json'; link.click(); URL.revokeObjectURL(url); flash('Backup exported.') }
  const importBackup = (file: File) => { const reader = new FileReader(); reader.onload = async () => { try { const parsed = JSON.parse(String(reader.result)); if (Array.isArray(parsed)) { await store.replace(parsed as KeepsyItem[]) } else if (parsed && typeof parsed === 'object' && Array.isArray(parsed.items)) { await store.replace(parsed.items as KeepsyItem[]); if (Array.isArray(parsed.collections)) await collectionStore.replace(parsed.collections as KeepsyCollection[]); if (parsed.taxonomy && Array.isArray(parsed.taxonomy.categories) && Array.isArray(parsed.taxonomy.tags)) { await saveTaxonomy(parsed.taxonomy); setTaxonomy(await loadTaxonomy()) } if (parsed.settings && typeof parsed.settings === 'object') { const merged = { ...defaultSettings, ...parsed.settings }; await saveSettings(merged); setSettings(merged) } } else throw new Error('invalid'); flash('Import complete.') } catch { flash('That file is not a valid Keepsy backup.') } }; reader.readAsText(file) }
  const updateSettings = async (partial: Partial<SettingsData>) => { const next = { ...settings, ...partial }; setSettings(next); await saveSettings(next) }
  const clearTrash = async () => { const remaining = store.items.filter(item => !item.deletedAt); if (remaining.length === store.items.length) return; await store.replace(remaining); flash('Trash emptied.') }
  const clearAllData = async () => { await store.replace([]); await collectionStore.replace([]); await resetTaxonomy(); setTaxonomy(await loadTaxonomy()); await saveSettings(defaultSettings); setSettings(defaultSettings); flash('All data cleared.') }
  const requestTrash = (item: KeepsyItem) => { if (settings.confirmBeforeDelete) setConfirm({ item, permanent: false }); else void deleteToTrash([item.id]) }
  const createCategory = async (name: string) => { await addTaxonomy('categories', name); setTaxonomy(await loadTaxonomy()) }
  const renameCategory = async (oldName: string, newName: string) => { const clean = newName.trim(); if (!clean) throw new Error('Enter a category name.'); if (taxonomy.categories.some(c => c.toLowerCase() === clean.toLowerCase() && c.toLowerCase() !== oldName.toLowerCase())) throw new Error('A category with this name already exists.'); await removeTaxonomy('categories', oldName); await addTaxonomy('categories', clean); const affected = store.items.filter(item => item.category === oldName).map(item => item.id); if (affected.length) await store.bulk(affected, { category: clean }); setTaxonomy(await loadTaxonomy()) }
  const deleteCategory = async (name: string) => { await removeTaxonomy('categories', name); const affected = store.items.filter(item => item.category === name).map(item => item.id); if (affected.length) await store.bulk(affected, { category: 'Personal' }); setTaxonomy(await loadTaxonomy()) }
  const createTag = async (name: string) => { await addTaxonomy('tags', name); setTaxonomy(await loadTaxonomy()) }
  const renameTag = async (oldName: string, newName: string) => { const clean = newName.trim(); if (!clean) throw new Error('Enter a tag name.'); if (taxonomy.tags.some(t => t.toLowerCase() === clean.toLowerCase() && t.toLowerCase() !== oldName.toLowerCase())) throw new Error('A tag with this name already exists.'); await removeTaxonomy('tags', oldName); await addTaxonomy('tags', clean); const affected = store.items.filter(item => item.tags.includes(oldName)).map(item => item.id); if (affected.length) await store.bulk(affected, { addTags: [clean], removeTags: [oldName] }); setTaxonomy(await loadTaxonomy()) }
  const deleteTag = async (name: string) => { await removeTaxonomy('tags', name); const affected = store.items.filter(item => item.tags.includes(name)).map(item => item.id); if (affected.length) await store.bulk(affected, { removeTags: [name] }); setTaxonomy(await loadTaxonomy()) }
  const categoryCounts = useMemo(() => Object.fromEntries(taxonomy.categories.map(name => [name, active.filter(item => item.category === name).length])), [taxonomy.categories, active])
  const tagCounts = useMemo(() => Object.fromEntries(taxonomy.tags.map(name => [name, active.filter(item => item.tags.includes(name)).length])), [taxonomy.tags, active])
  const customIconItems = useMemo(() => active.filter(item => !!item.customIcon), [active])
  const removeCustomIcon = (id: string) => { const item = store.items.find(i => i.id === id); if (item) void store.update(id, { ...item, customIcon: undefined }) }
  const save = async (draft: ItemDraft) => { if (draft.type === 'Crypto Wallet' && store.items.some(item => !item.deletedAt && item.type === 'Crypto Wallet' && item.walletAddress?.toLowerCase() === draft.walletAddress?.toLowerCase() && item.id !== (editor === 'new' ? undefined : editor?.id))) throw new Error('Duplicate wallet'); if (editor === 'new') await store.add(draft); else if (editor) await store.update(editor.id, draft); await collectionStore.touch(draft.collectionIds || []); setEditor(null); flash(editor === 'new' ? 'Item saved to Keepsy.' : 'Changes saved.') }
  const deleteCollection = async (id: string) => { await collectionStore.remove(id); await store.bulk(store.items.map(item => item.id), { removeCollections: [id] }); if (collectionFilter === id) setCollectionFilter(null); flash('Collection deleted.') }
  const saveQuickCollections = async () => { if (!quickCollectionItem) return; await store.update(quickCollectionItem.id, { ...quickCollectionItem, collectionIds: quickCollectionIds }); await collectionStore.touch(quickCollectionIds); setQuickCollectionItem(null); flash('Collections updated.') }
  const isDuplicate = (capture: CapturePayload) => { const value = capture.url || capture.email || capture.phone || capture.walletAddress || capture.content || capture.title; const normalized = value.trim().toLowerCase(); return store.items.some(item => !item.deletedAt && (item.url || item.email || item.phone || item.walletAddress || item.content || item.title).trim().toLowerCase() === normalized) }
  const saveCapture = async (draft: ItemDraft) => { await store.add(draft); await collectionStore.touch(draft.collectionIds || []); await clearPendingCapture(); setQuickCapture(null); flash('Capture saved to Keepsy.') }
  const cancelCapture = async () => { await clearPendingCapture(); setQuickCapture(null); flash('Capture dismissed.') }
  const copy = async (item: KeepsyItem) => { try { await navigator.clipboard.writeText(valueForCopy(item)); flash('Copied to clipboard.') } catch { flash('Copy is unavailable in this view.') } }
  const open = (item: KeepsyItem) => { if (item.url) window.open(item.url, '_blank', 'noopener,noreferrer'); else flash('This item does not have a link to open.') }
  const emptyText = filter === 'Trash' ? ['Trash is empty', 'Deleted items will stay here until you remove them forever.'] : query ? ['No matches found', 'Try another word, tag, or category.'] : ['Nothing here yet', 'Save your first item and Keepsy will keep it close.']
  return <MotionConfig reducedMotion={settings.animations ? 'never' : 'always'}><main className="relative h-[600px] w-[390px] overflow-hidden bg-midnight text-[#E6E8F0]">
    <div className="pointer-events-none absolute -right-32 -top-32 size-64 rounded-full bg-primary/[.08] blur-3xl" /><div className="relative flex h-full flex-col px-4 pb-4 pt-4">
      <header className="flex items-center justify-between px-1"><Brand /><div className="flex items-center gap-1"><Button variant={panel ? 'soft' : 'ghost'} onClick={() => setPanel(!panel)} className="size-10 rounded-xl p-0 active:scale-95" aria-label="Open filters"><SlidersHorizontal size={18} strokeWidth={1.8} /></Button><Button variant={filter === 'Trash' ? 'soft' : 'ghost'} onClick={() => setFilter(filter === 'Trash' ? 'All' : 'Trash')} className="size-10 rounded-xl p-0 active:scale-95" aria-label="Open trash"><Trash2 size={18} strokeWidth={1.8} /></Button><Button variant="ghost" title="Mini Games" onClick={() => setGamesHubOpen(true)} className="size-10 rounded-xl p-0 transition-transform duration-200 hover:-rotate-6 hover:scale-110 active:scale-95" aria-label="Mini Games"><Gamepad2 size={18} strokeWidth={1.8} /></Button><Button variant="ghost" onClick={() => setSettingsOpen(true)} className="size-10 rounded-xl p-0 active:scale-95" aria-label="Open settings"><Settings2 size={20} strokeWidth={1.8} /></Button></div></header>
      <label className="relative mt-4 block"><Search className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-[#81b0ff]" size={18} strokeWidth={1.8} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search titles, tags, and details" aria-label="Search saved items" className="w-full rounded-xl border border-line bg-surface py-3 pl-11 pr-4 text-[13px] text-[#E6E8F0] outline-none placeholder:text-muted/70 transition-all duration-200 hover:border-[#2B7FFF]/35 focus:border-primary/70 focus:ring-4 focus:ring-primary/10" /></label>
      <ProductivityPanel open={panel} types={[...itemTypes]} categories={taxonomy.categories} tags={taxonomy.tags} {...advanced} onChange={value => setAdvanced(current => ({ ...current, ...value }))} onExport={exportBackup} onImport={importBackup} />
      <div className="mt-5 flex items-center justify-between px-1"><div><h2 className="text-[14px] font-semibold tracking-[-.02em] text-white">{filter === 'Trash' ? 'Trash' : bulkMode ? `${selected.size} selected` : collectionFilter ? collectionStore.collections.find(collection => collection.id === collectionFilter)?.name || 'Collection' : 'Collection'}</h2><p className="mt-0.5 text-[11px] text-muted">{shown.length} item{shown.length === 1 ? '' : 's'}</p></div>{filter === 'Trash' ? <button onClick={() => setFilter('All')} className="text-[11px] font-medium text-[#81b0ff] transition hover:text-white focus:outline-none focus:ring-2 focus:ring-primary">Back to collection</button> : <button onClick={() => { setBulkMode(value => !value); setSelected(new Set()) }} className={`inline-flex items-center gap-1.5 rounded-lg px-2 py-1.5 text-[11px] font-medium transition ${bulkMode ? 'bg-primary/15 text-[#81b0ff]' : 'text-muted hover:bg-white/[.05] hover:text-white'}`}><ListChecks size={14} />{bulkMode ? 'Done' : 'Select'}</button>}</div>
      {filter !== 'Trash' && <nav className="mt-3 flex gap-1 rounded-xl border border-line bg-surface p-1" aria-label="Collection filters">{filters.map(name => <button key={name} onClick={() => setFilter(name)} className={`relative flex-1 rounded-lg px-2 py-2 text-[11px] font-medium transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-primary ${filter === name ? 'text-white' : 'text-muted hover:text-[#E6E8F0]'}`}>{filter === name && <motion.span layoutId="activeFilterTab" className="absolute inset-0 rounded-lg bg-card shadow-[0_1px_2px_rgba(0,0,0,.35)]" transition={{ type: 'spring', stiffness: 500, damping: 35 }} />}<span className="relative">{name}</span></button>)}</nav>}
      {filter !== 'Trash' && <section className="mt-3"><div className="mb-1.5 flex items-center justify-between px-1"><div className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[.08em] text-muted"><Layers3 size={12} />Collections</div><button onClick={() => setManageCollections(true)} className="text-[10px] font-medium text-[#81b0ff] hover:text-white">Manage</button></div>
        <div className="relative">
          {canScrollLeft && <div className="pointer-events-none absolute left-0 top-0 z-[5] h-full w-8 bg-gradient-to-r from-midnight to-transparent" />}
          <div ref={collectionsScrollRef} onScroll={updateCollectionsScroll} className={`no-scrollbar flex snap-x snap-proximity gap-1.5 overflow-x-auto scroll-smooth pb-1 ${canScrollLeft ? 'pl-6' : ''} ${canScrollRight ? 'pr-6' : ''}`}>
            <button ref={el => { if (el) pillRefs.current.set('all', el); else pillRefs.current.delete('all') }} onClick={() => setCollectionFilter(null)} className={`shrink-0 snap-start rounded-lg border px-2.5 py-1.5 text-[10px] font-medium transition ${!collectionFilter ? 'border-primary/60 bg-primary/25 text-white' : 'border-line bg-card text-muted hover:border-primary/30 hover:text-white'}`}>All</button>
            {collectionStore.collections.map(collection => { const color = labelColor(collection.name); const active = collectionFilter === collection.id; return <button key={collection.id} ref={el => { if (el) pillRefs.current.set(collection.id, el); else pillRefs.current.delete(collection.id) }} onClick={() => setCollectionFilter(current => current === collection.id ? null : collection.id)} className={`shrink-0 snap-start rounded-lg border px-2.5 py-1.5 text-[10px] font-medium transition ${active ? 'border-primary/60 bg-primary/25 text-white' : 'border-line bg-card text-muted hover:border-primary/30 hover:text-white'}`}><span className="mr-1 inline-block size-1.5 rounded-full align-middle" style={{ backgroundColor: color.text }} />{collection.name} <span className="ml-1 opacity-60">{collectionCounts[collection.id] || 0}</span></button> })}
          </div>
          {canScrollRight && <div className="pointer-events-none absolute right-0 top-0 z-[5] h-full w-8 bg-gradient-to-l from-midnight to-transparent" />}
          {canScrollLeft && <button aria-label="Scroll collections left" onClick={() => scrollCollections(-1)} className="absolute left-0 top-1/2 z-10 grid size-6 -translate-y-1/2 place-items-center rounded-full border border-line bg-card text-muted shadow-lg transition hover:text-white active:scale-90"><ChevronLeft size={13} /></button>}
          {canScrollRight && <button aria-label="Scroll collections right" onClick={() => scrollCollections(1)} className="absolute right-0 top-1/2 z-10 grid size-6 -translate-y-1/2 place-items-center rounded-full border border-line bg-card text-muted shadow-lg transition hover:text-white active:scale-90"><ChevronRight size={13} /></button>}
        </div>
      </section>}
      {bulkMode && filter !== 'Trash' && <div className="mt-2 flex items-center gap-1 rounded-xl border border-primary/20 bg-primary/[.07] p-1.5"><button onClick={() => setSelected(current => { const visibleIds = shown.map(item => item.id); const allVisibleSelected = visibleIds.every(id => current.has(id)); const next = new Set(current); visibleIds.forEach(id => allVisibleSelected ? next.delete(id) : next.add(id)); return next })} className="rounded-lg px-2 py-1.5 text-[10px] font-medium text-[#81b0ff] hover:bg-primary/10">{shown.length > 0 && shown.every(item => selected.has(item.id)) ? 'Deselect all' : 'Select all'}</button><div className="ml-auto flex gap-1"><button title="Move category" disabled={!selected.size} onClick={() => setBulkEditor('category')} className="grid size-7 place-items-center rounded-lg text-muted transition hover:bg-white/[.07] hover:text-white disabled:opacity-40"><FolderInput size={14} /></button><button title="Edit tags" disabled={!selected.size} onClick={() => setBulkEditor('tags')} className="grid size-7 place-items-center rounded-lg text-muted transition hover:bg-white/[.07] hover:text-white disabled:opacity-40"><Tag size={14} /></button><button title="Edit collections" disabled={!selected.size} onClick={() => setBulkEditor('collections')} className="grid size-7 place-items-center rounded-lg text-muted transition hover:bg-white/[.07] hover:text-[#81b0ff] disabled:opacity-40"><Layers3 size={14} /></button><button title="Move selected to Trash" disabled={!selected.size} onClick={() => setBulkDelete(true)} className="grid size-7 place-items-center rounded-lg text-[#ff9fb5] transition hover:bg-white/[.07] disabled:opacity-40"><Trash2 size={14} /></button></div></div>}
      <section className="mt-3 min-h-0 flex-1 overflow-y-auto px-0.5 pr-1 pb-12"><AnimatePresence mode="wait">{store.loading ? <div className="grid h-36 place-items-center text-sm text-muted"><LoaderCircle className="animate-spin" size={20} /></div> : store.error ? <div className="rounded-panel border border-[#6d3043] bg-[#21121a] p-4 text-xs text-[#ffb2c3]"><TriangleAlert size={16} className="mb-2" />{store.error}<button onClick={() => store.setError(null)} className="ml-2 underline">Dismiss</button></div> : shown.length === 0 ? <motion.div key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }}><EmptyState title={emptyText[0]} detail={emptyText[1]} /></motion.div> : <motion.div key={`${filter}-${collectionFilter || 'all'}`} className={settings.compactMode ? 'space-y-1' : 'space-y-2'}>{shown.map((item, index) => filter === 'Trash' ? <div key={item.id} className="flex items-center gap-2 rounded-panel border border-line bg-card px-3 py-3"><div className="min-w-0 flex-1"><p className="truncate text-[13px] font-medium text-[#E6E8F0]">{item.title}</p><p className="mt-0.5 text-[10px] text-muted">Deleted item</p></div><Button variant="ghost" onClick={() => { store.restore(item.id); flash('Item restored.') }} className="px-2 py-1 text-xs">Restore</Button><Button variant="ghost" onClick={() => setConfirm({ item, permanent: true })} className="px-2 py-1 text-xs text-[#ff9fb5]">Delete</Button></div> : <SaveItemCard key={item.id} item={item} index={index} collectionNames={(item.collectionIds || []).map(id => collectionStore.collections.find(collection => collection.id === id)?.name).filter((name): name is string => !!name)} selected={selected.has(item.id)} onSelect={bulkMode ? () => toggleSelected(item.id) : undefined} onEditCollections={() => { setQuickCollectionItem(item); setQuickCollectionIds(item.collectionIds || []) }} onView={() => { setDetail(item); void store.viewed(item.id) }} onCopy={() => copy(item)} onOpen={() => open(item)} onToggle={field => { store.toggle(item.id, field); flash(field === 'favorite' ? 'Favorite updated.' : 'Pin updated.') }} onEdit={() => setEditor(item)} onDelete={() => requestTrash(item)} compact={settings.compactMode} />)}</motion.div>}</AnimatePresence></section>
      {filter !== 'Trash' && <Button onClick={() => setEditor('new')} className="absolute bottom-7 right-4 rounded-xl px-4 py-3 text-[12px] shadow-[0_10px_24px_rgba(0,87,255,.28)] transition-all duration-200 hover:-translate-y-0.5 hover:shadow-[0_14px_30px_rgba(0,87,255,.4)] active:translate-y-0 active:scale-[.97]"><Plus size={17} strokeWidth={2.2} />Add new</Button>}
      <footer className="absolute bottom-2 left-4 text-[9px] font-medium tracking-[.02em] text-muted/45 transition hover:text-muted/70">Developed by: <a href="https://thinxify.com" target="_blank" rel="noreferrer" className="transition hover:text-[#81b0ff]">THINXIFY.COM</a></footer>
    </div>
    <Modal open={!!quickCapture} onClose={() => { void cancelCapture() }} title="Quick Save">{quickCapture && <QuickSaveForm capture={quickCapture} duplicate={isDuplicate(quickCapture)} collections={collectionStore.collections} onCreateCollection={collectionStore.create} onSave={saveCapture} onCancel={() => { void cancelCapture() }} />}</Modal>
    <Modal open={editor !== null} onClose={() => setEditor(null)} title={editor === 'new' ? 'Save something new' : 'Edit saved item'}>{editor && <ItemForm item={editor === 'new' ? undefined : editor} collections={collectionStore.collections} onCreateCollection={collectionStore.create} onSave={save} onCancel={() => setEditor(null)} />}</Modal>
    <Modal open={!!detail} onClose={() => { setDetail(null); setShowSecret(false) }} title={detail?.title || 'Saved item'}>{detail && <div className="space-y-4"><div className="grid size-11 place-items-center overflow-hidden rounded-xl border border-primary/20 bg-primary/10"><ItemIcon item={detail} className="size-full" /></div><div className="flex flex-wrap gap-1"><Badge tone="blue">{detail.type}</Badge><Badge color={labelColor(detail.category)}>{detail.category}</Badge>{detail.walletNetwork && <Badge>{detail.walletNetwork}</Badge>}{(detail.collectionIds || []).map(id => collectionStore.collections.find(collection => collection.id === id)).filter((collection): collection is NonNullable<typeof collection> => !!collection).map(collection => <Badge key={collection.id} color={labelColor(collection.name)}><Layers3 size={10} />{collection.name}</Badge>)}{detail.tags.map(t => <Badge key={t}>#{t}</Badge>)}</div>{detail.type === 'YouTube' && detail.youtubeThumbnail && <div><img src={detail.youtubeThumbnail} alt="Video thumbnail" className="h-36 w-full rounded-xl border border-line object-cover" />{detail.youtubeChannel && <p className="mt-1.5 text-[11px] text-muted">{detail.youtubeChannel}</p>}</div>}{detail.type === 'Website' && detail.url && <p className="text-[11px] text-muted">{domainFromUrl(detail.url)}</p>}{detail.type === 'Code' ? <pre className="max-h-48 overflow-auto rounded-xl border border-line bg-[#060810] p-3 font-mono text-xs leading-5">{highlightCode(detail.code || '')}</pre> : <pre className="max-h-48 whitespace-pre-wrap break-words rounded-xl border border-line bg-card p-3 font-sans text-xs leading-5 text-muted">{detail.type === 'API Key' && !showSecret ? '•'.repeat(20) : valueForCopy(detail)}</pre>}<div className="flex flex-wrap justify-between gap-2"><Button variant="ghost" onClick={() => { setDetail(null); setEditor(detail) }}>Edit</Button><div className="flex gap-2">{detail.type === 'API Key' && <Button variant="soft" onClick={() => setShowSecret(!showSecret)}>{showSecret ? <EyeOff size={14} /> : <Eye size={14} />}{showSecret ? 'Hide' : 'Reveal'}</Button>}<Button variant="soft" onClick={() => copy(detail)}>Copy</Button>{detail.type === 'Crypto Wallet' && detail.walletAddress && <Button variant="soft" onClick={() => setQrItem(detail)}><QrCode size={14} />QR</Button>}{detail.type === 'Crypto Wallet' && detail.walletAddress ? <Button onClick={() => window.open(walletExplorer(detail.walletNetwork || 'ETH', detail.walletAddress!), '_blank', 'noopener,noreferrer')}>Explorer</Button> : detail.url && <Button onClick={() => open(detail)}>Open link</Button>}</div></div><button onClick={() => { const target = detail; setDetail(null); requestTrash(target) }} className="text-xs text-[#ff9fb5]">Move to trash</button></div>}</Modal>
    <Modal open={!!qrItem} onClose={() => setQrItem(null)} title="Wallet QR code">{qrItem?.walletAddress && <div className="space-y-4 text-center"><WalletQr address={qrItem.walletAddress} /><p className="break-all text-xs leading-5 text-muted">{qrItem.walletAddress}</p><Button variant="soft" onClick={() => copy(qrItem)}>Copy address</Button></div>}</Modal>
    <Modal open={!!quickCollectionItem} onClose={() => setQuickCollectionItem(null)} title="Quick Collections">{quickCollectionItem && <div className="space-y-5"><p className="text-xs leading-5 text-muted">Add or remove “{quickCollectionItem.title}” from Collections.</p><CollectionSelect collections={collectionStore.collections} value={quickCollectionIds} onChange={setQuickCollectionIds} onCreate={collectionStore.create} /><div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setQuickCollectionItem(null)}>Cancel</Button><Button onClick={() => { void saveQuickCollections() }}>Save</Button></div></div>}</Modal>
    <Modal open={bulkEditor === 'category' || bulkEditor === 'tags'} onClose={() => setBulkEditor(null)} title={bulkEditor === 'category' ? 'Move selected items' : 'Edit selected tags'}>{bulkEditor === 'category' ? <div className="space-y-5"><p className="text-xs leading-5 text-muted">Choose one category for {selected.size} selected items.</p><SearchableSelect kind="categories" label="Category" value={bulkCategory} onChange={value => setBulkCategory(value as string)} placeholder="Choose category" /><div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setBulkEditor(null)}>Cancel</Button><Button disabled={!bulkCategory} onClick={() => { void applyBulk() }}>Move items</Button></div></div> : <div className="space-y-5"><p className="text-xs leading-5 text-muted">Apply tags to {selected.size} selected items.</p><div className="flex rounded-lg border border-line p-1 text-xs"><button onClick={() => setTagOperation('add')} className={`flex-1 rounded-md py-1.5 ${tagOperation === 'add' ? 'bg-primary/15 text-[#81b0ff]' : 'text-muted'}`}>Add tags</button><button onClick={() => setTagOperation('remove')} className={`flex-1 rounded-md py-1.5 ${tagOperation === 'remove' ? 'bg-primary/15 text-[#81b0ff]' : 'text-muted'}`}>Remove tags</button></div><SearchableSelect kind="tags" label="Tags" multiple value={bulkTags} onChange={value => setBulkTags(value as string[])} placeholder="Choose tags" /><div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setBulkEditor(null)}>Cancel</Button><Button disabled={!bulkTags.length} onClick={() => { void applyBulk() }}>{tagOperation === 'add' ? 'Add tags' : 'Remove tags'}</Button></div></div>}</Modal>
    <Modal open={bulkEditor === 'collections'} onClose={() => setBulkEditor(null)} title="Edit selected Collections"><div className="space-y-5"><p className="text-xs leading-5 text-muted">Update Collections for {selected.size} selected items.</p><div className="flex rounded-lg border border-line p-1 text-xs"><button onClick={() => setCollectionOperation('add')} className={`flex-1 rounded-md py-1.5 ${collectionOperation === 'add' ? 'bg-primary/15 text-[#81b0ff]' : 'text-muted'}`}>Assign</button><button onClick={() => setCollectionOperation('remove')} className={`flex-1 rounded-md py-1.5 ${collectionOperation === 'remove' ? 'bg-primary/15 text-[#81b0ff]' : 'text-muted'}`}>Remove</button></div><CollectionSelect collections={collectionStore.collections} value={bulkCollections} onChange={setBulkCollections} onCreate={collectionStore.create} /><div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setBulkEditor(null)}>Cancel</Button><Button disabled={!bulkCollections.length} onClick={() => { void applyBulk() }}>{collectionOperation === 'add' ? 'Assign Collections' : 'Remove Collections'}</Button></div></div></Modal>
    <Modal open={bulkDelete} onClose={() => setBulkDelete(false)} title="Move selected items to Trash?"><p className="text-sm leading-6 text-muted">{selected.size} selected item{selected.size === 1 ? '' : 's'} will be moved to Trash. You can undo this immediately or restore them later.</p><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setBulkDelete(false)}>Cancel</Button><Button onClick={() => { void deleteToTrash(selectedIds); setBulkDelete(false) }} className="bg-[#c94166] hover:brightness-110">Move to Trash</Button></div></Modal>
    <Modal open={!!confirm} onClose={() => setConfirm(null)} title={confirm?.permanent ? 'Delete permanently?' : 'Move to trash?'}><p className="text-sm leading-6 text-muted">{confirm?.permanent ? `This will permanently remove “${confirm.item.title}” and cannot be undone.` : `“${confirm?.item.title}” can be restored from Trash later.`}</p><div className="mt-5 flex justify-end gap-2"><Button variant="ghost" onClick={() => setConfirm(null)}>Cancel</Button><Button onClick={() => { if (confirm) { if (confirm.permanent) { store.remove(confirm.item.id); flash('Item permanently deleted.') } else { void deleteToTrash([confirm.item.id]) } setConfirm(null) } }} className="bg-[#c94166] hover:brightness-110">{confirm?.permanent ? 'Delete forever' : 'Move to trash'}</Button></div></Modal>
    <AnimatePresence>{notice && <motion.div role="status" initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 8 }} className="absolute bottom-5 left-5 z-30 flex items-center gap-2 rounded-xl border border-line bg-surface px-3 py-2 text-xs shadow-lg"><CheckCircle2 size={15} className="text-accent" />{notice}{undoItems && <button onClick={() => { void undoDelete() }} className="ml-1 rounded-md bg-primary/15 px-2 py-1 font-semibold text-[#81b0ff] transition hover:bg-primary/25">Undo</button>}<button aria-label="Dismiss notification" onClick={() => setNotice(null)} className="ml-1 text-muted hover:text-white"><X size={13} /></button></motion.div>}</AnimatePresence>
    <AnimatePresence>{settingsOpen && <Settings
      onClose={() => setSettingsOpen(false)}
      settings={settings}
      onChangeSettings={value => { void updateSettings(value) }}
      trashCount={trashed.length}
      onClearTrash={() => { void clearTrash() }}
      onClearAllData={() => { void clearAllData() }}
      onExportBackup={exportBackup}
      onImportBackup={importBackup}
      onManageCollections={() => setManageCollections(true)}
      onManageCategories={() => setManageCategories(true)}
      onManageTags={() => setManageTags(true)}
      onViewCustomIcons={() => setCustomIconsOpen(true)}
      onViewOnboarding={() => { setSettingsOpen(false); setOnboardingOpen(true) }}
      onPlayGame2048={() => { setSettingsOpen(false); setGamesHubOpen(true) }}
      customIconItems={customIconItems}
      storageBytes={storageBytes}
      version={typeof chrome !== 'undefined' && chrome.runtime?.getManifest ? chrome.runtime.getManifest().version : '0.1.0'}
    />}</AnimatePresence>
    <Modal open={manageCollections} onClose={() => setManageCollections(false)} title="Manage Collections"><CollectionManager collections={collectionStore.collections} counts={collectionCounts} onCreate={collectionStore.create} onRename={collectionStore.rename} onDelete={deleteCollection} /></Modal>
    <Modal open={manageCategories} onClose={() => setManageCategories(false)} title="Manage Categories"><TaxonomyManager noun="Category" items={taxonomy.categories} counts={categoryCounts} onCreate={createCategory} onRename={renameCategory} onDelete={deleteCategory} deleteNote={name => `${categoryCounts[name] || 0} item${categoryCounts[name] === 1 ? '' : 's'} using “${name}” will be moved to “Personal”.`} showColor /></Modal>
    <Modal open={manageTags} onClose={() => setManageTags(false)} title="Manage Tags"><TaxonomyManager noun="Tag" items={taxonomy.tags} counts={tagCounts} onCreate={createTag} onRename={renameTag} onDelete={deleteTag} deleteNote={name => `${tagCounts[name] || 0} item${tagCounts[name] === 1 ? '' : 's'} will lose the “${name}” tag.`} /></Modal>
    <Modal open={customIconsOpen} onClose={() => setCustomIconsOpen(false)} title="Custom Icons"><CustomIconsGallery items={customIconItems} onRemove={removeCustomIcon} /></Modal>
    <AnimatePresence>{onboardingOpen && <Onboarding onDone={finishOnboarding} />}</AnimatePresence>
    <AnimatePresence>{gamesHubOpen && <Suspense fallback={<div className="absolute inset-0 z-30 grid place-items-center bg-midnight"><Gamepad2 className="animate-pulse text-muted" size={28} strokeWidth={1.6} /></div>}><GamesHub onClose={() => setGamesHubOpen(false)} onPlayTapTheDot={() => { setGamesHubOpen(false); setTapTheDotOpen(true) }} /></Suspense>}</AnimatePresence>
    <AnimatePresence>{tapTheDotOpen && <Suspense fallback={<div className="absolute inset-0 z-30 grid place-items-center bg-midnight"><img src="/game-logo-dot.png" alt="" className="size-14 animate-pulse object-contain" /></div>}><TapTheDot onClose={() => { setTapTheDotOpen(false); setGamesHubOpen(true) }} /></Suspense>}</AnimatePresence>
  </main></MotionConfig>
}
